version: '3'

# https://taskfile.dev/usage/#env-files
dotenv: ['.env.local', '.env']

vars:
  DOCKER_COMPOSE: '{{.TASK_DOCKER_COMPOSE | default "docker compose"}}'

tasks:
  compose:
    cmds:
      - '{{.DOCKER_COMPOSE}} {{.CLI_ARGS}}'

  composer:
    cmds:
      - task compose -- run --rm phpfpm composer {{.CLI_ARGS}}
    silent: true

  coding-standards:apply:
    desc: "Apply coding standards"
    cmds:
      # - task: coding-standards:assets:apply
      - task: coding-standards:composer:apply
      - task: coding-standards:markdown:apply
      - task: coding-standards:php:apply
      - task: coding-standards:twig:apply
      - task: coding-standards:yaml:apply
    silent: true

  coding-standards:check:
    desc: "Apply coding standards"
    cmds:
      # - task: coding-standards:assets:check
      - task: coding-standards:composer:check
      - task: coding-standards:markdown:check
      - task: coding-standards:php:check
      - task: coding-standards:twig:check
      - task: coding-standards:yaml:check
    silent: true

  # coding-standards:assets:apply:
  #   desc: "Apply coding standards for assets"
  #   cmds:
  #     - task compose -- run --rm prettier 'assets/' --write

  # coding-standards:assets:check:
  #   desc: "Apply and check coding standards for assets"
  #   cmds:
  #     - task: coding-standards:assets:apply
  #     - task compose -- run --rm prettier 'assets/' --check

  coding-standards:composer:apply:
    desc: "Apply coding standards for Composer"
    cmds:
      - task composer -- normalize

  coding-standards:composer:check:
    desc: "Apply and check coding standards for Composer"
    cmds:
      - task: coding-standards:composer:apply
      - task composer -- audit
      - task composer -- normalize --dry-run
      - task composer -- validate --strict

  coding-standards:markdown:apply:
    desc: "Apply coding standards for Markdown"
    cmds:
      - task compose -- run --rm markdownlint '**/*.md' --fix

  coding-standards:markdown:check:
    desc: "Apply and check coding standards for Markdown"
    cmds:
      - task: coding-standards:markdown:apply
      - task compose -- run --rm markdownlint '**/*.md'

  coding-standards:php:apply:
    desc: "Apply coding standards for PHP"
    cmds:
      - task compose -- run --rm phpfpm vendor/bin/rector
      - task compose -- run --rm phpfpm vendor/bin/php-cs-fixer fix
    silent: true

  coding-standards:php:check:
    desc: "Apply and check coding standards for PHP"
    cmds:
      - task: coding-standards:php:apply
      - task compose -- run --rm phpfpm vendor/bin/rector --dry-run
      - task compose -- run --rm phpfpm vendor/bin/php-cs-fixer check
    silent: true

  coding-standards:twig:apply:
    desc: "Apply coding standards for Twig"
    cmds:
      - task compose -- run --rm phpfpm vendor/bin/twig-cs-fixer fix
    silent: true

  coding-standards:twig:check:
    desc: "Apply and check coding standards for Twig"
    cmds:
      - task: coding-standards:twig:apply
      - task compose -- run --rm phpfpm vendor/bin/twig-cs-fixer check
    silent: true

  coding-standards:yaml:apply:
    desc: "Apply coding standards for YAML"
    cmds:
      - task compose -- run --rm prettier --parser yaml phpstan*.neon 'config/**/*.{yml,yaml}' --write

  coding-standards:yaml:check:
    desc: "Apply and check coding standards for YAML"
    cmds:
      - task: coding-standards:yaml:apply
      - task compose -- run --rm prettier --parser yaml phpstan*.neon 'config/**/*.{yml,yaml}' --check

  code-analysis:
    cmds:
      - task compose -- run --rm phpfpm vendor/bin/phpstan

  default:
    cmds:
      - task --list-all
    silent: true
